package boulangerie;

public enum EnumRecette {
    CHOUX_VANILLE_CHANTILLY_NOISETTES,
    CHOUX_VANILLE_CHANTILLY_AMANDES,
    CHOUX_VANILLE_CHANTILLY,
    CHOUX_VANILLE_NOISETTES,
    CHOUX_VANILLE_AMANDES,
    CHOUX_VANILLE,
    CHOUX_CHOCOLAT_CHANTILLY_NOISETTES,
    CHOUX_CHOCOLAT_CHANTILLY_AMANDES,
    CHOUX_CHOCOLAT_CHANTILLY,
    CHOUX_CHOCOLAT_NOISETTES,
    CHOUX_CHOCOLAT_AMANDES,
    CHOUX_CHOCOLAT,

    TARTE_POMME_MERINGUE_NOISETTES,
    TARTE_POMME_MERINGUE_AMANDES,
    TARTE_POMME_MERINGUE,
    TARTE_POMME_NOISETTES,
    TARTE_POMME_AMANDES,
    TARTE_POMME,
    TARTE_ABRICOT_MERINGUE_NOISETTES,
    TARTE_ABRICOT_MERINGUE_AMANDES,
    TARTE_ABRICOT_MERINGUE,
    TARTE_ABRICOT_NOISETTES,
    TARTE_ABRICOT_AMANDES,
    TARTE_ABRICOT,
}
